language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - PACKAGE_VERSION=high

sudo: false

matrix:
  include:
    - php: 7.2
      env: PACKAGE_VERSION=low

before_script:
  - composer selfupdate
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-dist; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-dist; fi

script: vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#jackalope"
