language: php

php:
  - 5.5

sudo: false

before_script:
  - composer selfupdate
  - composer install

script: 
    - php vendor/bin/phpunit
    - php vendor/bin/phpbench run --iterations=2

matrix:
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#jackalope"
